name: Compile
on:
  release:
    types: [created]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: "x86_64-pc-windows-msvc"
            output_name: "downloader.exe"
          - target: "aarch64-apple-darwin"
            output_name: "downloader-apple-silicon"
          - target: "x86_64-unknown-linux-gnu"
            output_name: "downloader-linux-x86"
          - target: "aarch64-unknown-linux-gnu"
            output_name: "downloader-linux-arm"

    permissions:
      id-token: write # Needed for auth with Deno Compile
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: "deno i"

      - name: Compile step
        run: "deno compile --allow-net --allow-read --allow-write --target ${{ matrix.target }} --output ${{ matrix.output_name }} main.ts"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-files
          path: ${{ matrix.output_name }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: compiled-files
          path: ./artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
